"""LaTeX tables and number macros, so the paper's text is generated from results."""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pandas as pd


def _fmt(x, nd=1, signed=False):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "--"
    s = f"{x:+.{nd}f}" if signed else f"{x:.{nd}f}"
    return tex_minus(s)


def tex_minus(s: str) -> str:
    """A typographic minus that works in text and in math mode."""
    return "\\ensuremath{-}" + s[1:] if s.startswith("-") else s


def macro_name(key: str) -> str:
    """'es_red.ratchet' -> '\\EsRedRatchet' (letters only, as LaTeX requires)."""
    if re.search(r"\d", key):
        raise ValueError(f"LaTeX macro names cannot contain digits: {key!r}")
    return "\\" + "".join(p[0].upper() + p[1:] for p in re.split(r"[^A-Za-z]+", key) if p)


def write_numbers(values: dict[str, str | float], path: str | Path, nd: int = 1):
    lines = ["% generated by scripts/run_paper.py -- do not edit"]
    for k, v in values.items():
        text = tex_minus(v) if isinstance(v, str) else _fmt(float(v), nd)
        lines.append(f"\\newcommand{{{macro_name(k)}}}{{{text}}}")
    Path(path).write_text("\n".join(lines) + "\n")


def table_calibration(calib: pd.DataFrame, targets: list[tuple[str, str, str, int]], path: str | Path):
    """Simulated moments (median and 5-95% range across paths) next to their empirical anchors."""
    rows = []
    for col, label, anchor, nd in targets:
        q = calib[col].quantile([0.05, 0.5, 0.95])
        rows.append(f"{label} & {_fmt(q[0.5], nd)} & [{_fmt(q[0.05], nd)}, {_fmt(q[0.95], nd)}] & {anchor} \\\\")
    body = "\n".join(rows)
    Path(path).write_text(
        "\\begin{tabular}{@{}lrcl@{}}\n\\toprule\n"
        "Moment & Median & 5--95\\% & Empirical anchor \\\\\n\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n")


def table_forecasts(summary: pd.DataFrame, path: str | Path):
    hs = sorted(summary["h"].unique())
    models = list(dict.fromkeys(summary["model"]))
    head = " & ".join([f"\\multicolumn{{3}}{{c}}{{$h={h}$ day{'s' if h > 1 else ''}}}" for h in hs])
    cmid = " ".join([f"\\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(hs))])
    sub = " & ".join(["QL ratio & MZ $R^2$ & DM win" for _ in hs])
    rows = []
    for m in models:
        cells = []
        for h in hs:
            r = summary[(summary.h == h) & (summary.model == m)].iloc[0]
            best = summary[summary.h == h]["qlike_ratio"].min()
            ql = _fmt(r["qlike_ratio"], 2)
            ql = f"\\textbf{{{ql}}}" if np.isclose(r["qlike_ratio"], best) else ql
            win = "--" if m == "HAR" else f"{r['dm_win']:.0f}\\%"
            cells += [ql, _fmt(r["mz_r2"], 2), win]
        rows.append(f"{m} & " + " & ".join(cells) + " \\\\")
    Path(path).write_text(
        f"\\begin{{tabular}}{{@{{}}l{'rrr' * len(hs)}@{{}}}}\n\\toprule\n & {head} \\\\\n{cmid}\n"
        f"Model & {sub} \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_hedging(med: pd.DataFrame, order: list[tuple[str, str]], cols: list[tuple[str, str, int]], path: str | Path):
    """Strategies as rows, metrics as columns (medians across test paths)."""
    head = " & ".join(c[1] for c in cols)
    rows = []
    for key, label in order:
        cells = [_fmt(med.loc[key, c], nd) for c, _, nd in cols]
        rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    Path(path).write_text(
        f"\\begin{{tabular}}{{@{{}}l{'r' * len(cols)}@{{}}}}\n\\toprule\nRule & {head} \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_robustness(rows: list[dict], path: str | Path):
    labels = {"Trading costs x2": "Trading costs $\\times$2", "Trading costs x0.5": "Trading costs $\\times$0.5",
              "Funding carry 0": "Carry 0 vol pts", "Funding carry 12": "Carry 12 vol pts"}
    body = []
    for r in rows:
        body.append(
            f"{labels.get(r['scenario'], r['scenario'])} & {_fmt(r['es_always'])} & {_fmt(r['es_ratchet'])} & "
            f"{_fmt(r['d_mean'], 2, True)} [{_fmt(r['d_lo'], 2, True)}, {_fmt(r['d_hi'], 2, True)}] & "
            f"{r['share']:.0f}\\% & {_fmt(r['es_switch'])} & {_fmt(r['cost_always'], 2)} & {_fmt(r['cost_ratchet'], 2)} \\\\")
    Path(path).write_text(
        "\\begin{tabular}{@{}lrrcrrrr@{}}\n\\toprule\n"
        " & \\multicolumn{2}{c}{ES red. (\\%)} & Ratchet $-$ Always & & Switch & \\multicolumn{2}{c}{Cost (\\% p.a.)} \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){7-8}\n"
        "Scenario & Always & Ratchet & mean [95\\% CI] & $>0$ & ES red. & Always & Ratchet \\\\\n\\midrule\n"
        + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n")
