"""LaTeX tables and number macros, so the paper's text is generated from results."""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pandas as pd


def _fmt(x, nd=1, signed=False):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "--"
    if float(f"{x:.{nd}f}") == 0:
        x = 0.0                                           # never print a negative zero
    s = f"{x:+.{nd}f}" if signed and x != 0 else f"{x:.{nd}f}"
    return tex_minus(s)


def tex_minus(s: str) -> str:
    """A typographic minus, in text and math mode, for every negative number in ``s`` (e.g. '[-0.22, +4.89]')."""
    return re.sub(r"(?<![\w.])-(?=\d)", lambda _: "\\ensuremath{-}", s)


def macro_name(key: str) -> str:
    """'es_red.ratchet' -> '\\EsRedRatchet' (letters only, as LaTeX requires)."""
    if re.search(r"\d", key):
        raise ValueError(f"LaTeX macro names cannot contain digits: {key!r}")
    return "\\" + "".join(p[0].upper() + p[1:] for p in re.split(r"[^A-Za-z]+", key) if p)


def write_numbers(values: dict[str, str | float], path: str | Path, nd: int = 1):
    lines = ["% generated by scripts/run_paper.py -- do not edit"]
    for k, v in values.items():
        text = tex_minus(v) if isinstance(v, str) else _fmt(float(v), nd)
        lines.append(f"\\newcommand{{{macro_name(k)}}}{{{text}}}")
    Path(path).write_text("\n".join(lines) + "\n")


def table_hedging(med: pd.DataFrame, order: list[tuple[str, str]], cols: list[tuple[str, str, int]], path: str | Path):
    """Strategies as rows, metrics as columns (medians across test paths)."""
    head = " & ".join(c[1] for c in cols)
    rows = []
    for key, label in order:
        cells = [_fmt(med.loc[key, c], nd) for c, _, nd in cols]
        rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    Path(path).write_text(
        f"\\begin{{tabular}}{{@{{}}l{'r' * len(cols)}@{{}}}}\n\\toprule\nRule & {head} \\\\\n\\midrule\n"
        + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


# --------------------------------------------------------------------------- live data
def table_live_forecasts(evals: pd.DataFrame, path: str | Path):
    """Single path: QLIKE ratio to HAR, Mincer-Zarnowitz R^2 and the Diebold-Mariano t-statistic vs HAR."""
    hs = sorted(evals["h"].unique())
    models = [m for m in ("RW", "EWMA", "GARCH", "HAR", "IV-raw", "IV", "HAR-IV") if m in set(evals["model"])]
    head = " & ".join([f"\\multicolumn{{3}}{{c}}{{$h={h}$ day{'s' if h > 1 else ''}}}" for h in hs])
    cmid = " ".join([f"\\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(hs))])
    sub = " & ".join(["QL ratio & MZ $R^2$ & DM $t$" for _ in hs])
    rows = []
    for m in models:
        cells = []
        for h in hs:
            e = evals[evals.h == h].set_index("model")
            ratio = e.loc[m, "qlike"] / e.loc["HAR", "qlike"]
            best = (e["qlike"] / e.loc["HAR", "qlike"]).min()
            ql = _fmt(ratio, 2)
            ql = f"\\textbf{{{ql}}}" if np.isclose(ratio, best) else ql
            dm = "--" if m == "HAR" else _fmt(e.loc[m, "dm_vs_HAR"], 2)
            cells += [ql, _fmt(e.loc[m, "mz_r2"], 2), dm]
        rows.append(f"{m} & " + " & ".join(cells) + " \\\\")
    Path(path).write_text(
        f"\\begin{{tabular}}{{@{{}}l{'rrr' * len(hs)}@{{}}}}\n\\toprule\n & {head} \\\\\n{cmid}\n"
        f"Model & {sub} \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")


def table_live_vs_sim(live: dict, sim: pd.DataFrame, rows: list[tuple[str, str, str, int]], path: str | Path):
    """Stylised facts: live sample (full and by year) next to the simulation's median."""
    years = list(live["by_year"].keys())
    head = " & ".join(["Live"] + years + ["Sim."])
    body = []
    for key, label, year_key, nd in rows:
        cells = [_fmt(live[key], nd)]
        cells += [_fmt(live["by_year"][y][year_key], nd) if year_key else "" for y in years]
        cells += [_fmt(sim[key].median(), nd) if key in sim else "--"]
        body.append(f"{label} & " + " & ".join(cells) + " \\\\")
    Path(path).write_text(
        f"\\begin{{tabular}}{{@{{}}l{'r' * (len(years) + 2)}@{{}}}}\n\\toprule\nMoment & {head} \\\\\n\\midrule\n"
        + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n")


def table_live_sensitivity(sens: dict, rules: list[tuple[str, str]], path: str | Path):
    """ES reduction (and hedge-leg P&L net of funding and trading costs) of the frozen rules under live perturbations."""
    head = " & ".join(label for _, label in rules)
    body = []
    for scen, d in sens.items():
        cells = [f"{_fmt(d[k]['es_red'])} ({_fmt(d[k]['hedge_pnl'] - d[k]['cost'], 1, True)})" for k, _ in rules]
        label = {"book costs": "Book costs (50 bp + fee)"}.get(scen, scen[0].upper() + scen[1:])
        body.append(f"{label} & " + " & ".join(cells) + " \\\\")
    Path(path).write_text(
        f"\\begin{{tabular}}{{@{{}}l{'r' * len(rules)}@{{}}}}\n\\toprule\nVariant & {head} \\\\\n\\midrule\n"
        + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n")
